---
- name: Install and setup nginx
  hosts: localhost
  become: yes
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: latest
    
    - name: setup nginx config
      template:
        src: nginx_config.j2
        dest: /etc/nginx/sites-available/default

    - name: setup index.html
      template:
        src: index.html.j2
        dest: /var/www/html/index.html

    - name: start nginx
      service:
        name: nginx
        state: started
