---
- name: Install and setup nginx
  hosts: localhost
  become: yes
  tasks:
    - name: install nginx
      apt:
        name: nginx
        state: latest
    
    - name: setup nginx config
      template:
        src: nginx_config.j2
        dest: /etc/nginx/sites-available/my_site

    - name: link site config
      shell: ln -s /etc/nginx/sites-available/my_site /etc/nginx/sites-enabled/

    - name: setup index.html
      template:
        src: index.html.j2
        dest: /var/www/html/my_site_index.html

    - name: start nginx
      service:
        name: nginx
        state: started
